blank_issues_enabled: false
contact_links:
  - name: Security vulnerability reporting
    url: https://tidelift.com/security
    about: Please report security issues through the private security channel.
